# Generated by Django 5.2.1 on 2025-05-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_sold_out_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold_out',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
