# Generated by Django 5.2.1 on 2025-05-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default='[]', help_text='List of items and quantities, stored as plain text or JSON.'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
