# Generated by Django 5.2.1 on 2025-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_items_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(help_text='List of items and quantities, stored as plain text.'),
        ),
    ]
